from __future__ import annotations
from typing import Protocol, Optional, List, Tuple, Dict
from uuid import UUID
from datetime import datetime
from .dto import ReminderDTO, ReminderNoteDTO

class IReminderRepo(Protocol):
    def find_duplicate(self, *, user_id: UUID, title: str, application_id: Optional[UUID], due_date: datetime) -> Optional[ReminderDTO]: ...
    def create(self, *, user_id: UUID, title: str, description: Optional[str], due_date: datetime, application_id: Optional[UUID]) -> ReminderDTO: ...
    def get_owned(self, *, user_id: UUID, reminder_id: UUID) -> ReminderDTO: ...
    def update(self, *, user_id: UUID, reminder_id: UUID, data: Dict) -> ReminderDTO: ...
    def list_for_user(self, *, user_id: UUID, skip: int, limit: int) -> List[ReminderDTO]: ...
    def delete_owned(self, *, user_id: UUID, reminder_id: UUID) -> None: ...
    def set_google_fields(self, *, user_id: UUID, reminder_id: UUID, google_event_id: Optional[str], meet_url: Optional[str]) -> ReminderDTO: ...

class IReminderNoteRepo(Protocol):
    def list_for_reminder(self, *, user_id: UUID, reminder_id: UUID) -> List[ReminderNoteDTO]: ...
    def create(self, *, user_id: UUID, reminder_id: UUID, body: str) -> ReminderNoteDTO: ...
    def update_owned(self, *, user_id: UUID, note_id: UUID, body: str) -> ReminderNoteDTO: ...
    def delete_owned(self, *, user_id: UUID, note_id: UUID) -> None: ...
    def delete_all_for_reminder(self, *, reminder_id: UUID) -> None: ...

class ICalendarGateway(Protocol):
    async def is_connected(self, *, user_id: UUID) -> bool: ...
    async def create_event(
        self, *, user_id: UUID, title: str, description: str | None,
        start: datetime, end: datetime, timezone_str: str, calendar_id: str,
        add_meet_link: bool, private_props: Optional[dict] = None
    ) -> Tuple[str, Optional[str]]: ...
    async def update_event(
        self, *, user_id: UUID, event_id: str, title: Optional[str], description: Optional[str],
        start: Optional[datetime], end: Optional[datetime], timezone_str: Optional[str] = None, calendar_id: str = "primary"
    ) -> None: ...
    async def delete_event(self, *, user_id: UUID, event_id: str, calendar_id: str = "primary") -> None: ...
    async def get_event(self, *, user_id: UUID, event_id: str, calendar_id: str = "primary") -> dict: ...
    async def list_events(self, *, user_id: UUID, calendar_id: str = "primary",
                          time_min: Optional[str] = None, time_max: Optional[str] = None, max_results: int = 100) -> List[dict]: ...
