from __future__ import annotations
from typing import Optional, List, Tuple, Dict
from uuid import UUID
from .dto import JobDTO

class ICompanyRepository:
    def get_id_by_name(self, name: str) -> Optional[UUID]: ...
    def ensure_company(self, name: str, website: Optional[str], location: Optional[str]) -> UUID: ...

class IJobRepository:
    def create(self, *, user_id: UUID, company_id: Optional[UUID], payload: Dict) -> JobDTO: ...
    def get_for_user_with_company(self, job_id: UUID, user_id: UUID) -> JobDTO: ...
    def list_for_user(
        self,
        user_id: UUID,
        page: int,
        page_size: int,
        filters: Dict,
        sort: str,
        order: str,
    ) -> Tuple[List[JobDTO], int]:
        ...
    def update_for_user(self, job_id: UUID, user_id: UUID, data: Dict) -> JobDTO: ...
    def delete_for_user_cascade(self, job_id: UUID, user_id: UUID) -> None: ...

class ISearchGateway:
    def search_jobs(self, *, query_text: str, limit: int, offset: int, filters: Dict) -> List[dict]: ...
    def count(self, query_text: str, filters: Dict) -> int: ...
    def suggest(self, q: str, user_id: str) -> List[str]: ...
