from __future__ import annotations
from typing import Protocol, List, Dict, Iterable
from uuid import UUID
from datetime import datetime
from .dto import ApplicationLiteDTO, StageLiteDTO, JobLiteDTO, CompanyLiteDTO

class IAnalyticsReadRepo(Protocol):
    def list_user_applications_since(self, *, user_id: UUID, start_date: datetime) -> List[ApplicationLiteDTO]: ...
    def list_stages_for_applications(self, *, app_ids: Iterable[UUID]) -> List[StageLiteDTO]: ...
    def map_jobs(self, *, job_ids: Iterable[UUID]) -> Dict[UUID, JobLiteDTO]: ...
    def map_companies(self, *, company_ids: Iterable[UUID]) -> Dict[UUID, CompanyLiteDTO]: ...
