/**
 * Hebrew translations for countries
 */

export const COUNTRY_NAMES_HEBREW: Record<string, string> = {
  'Afghanistan': 'אפגניסטן',
  'Albania': 'אלבניה',
  'Algeria': 'אלג\'יריה',
  'American Samoa': 'סמואה האמריקנית',
  'Andorra': 'אנדורה',
  'Angola': 'אנגולה',
  'Anguilla': 'אנגווילה',
  'Antarctica': 'אנטארקטיקה',
  'Antigua and Barbuda': 'אנטיגואה וברבודה',
  'Argentina': 'ארגנטינה',
  'Armenia': 'ארמניה',
  'Aruba': 'ארובה',
  'Australia': 'אוסטרליה',
  'Austria': 'אוסטריה',
  'Azerbaijan': 'אזרבייג\'ן',
  'Bahamas': 'איי בהאמה',
  'Bahrain': 'בחריין',
  'Bangladesh': 'בנגלדש',
  'Barbados': 'ברבדוס',
  'Belarus': 'בלארוס',
  'Belgium': 'בלגיה',
  'Belize': 'בליז',
  'Benin': 'בנין',
  'Bermuda': 'ברמודה',
  'Bhutan': 'בהוטן',
  'Bolivia': 'בוליביה',
  'Bosnia and Herzegovina': 'בוסניה והרצגובינה',
  'Botswana': 'בוצואנה',
  'Brazil': 'ברזיל',
  'British Indian Ocean Territory': 'הטריטוריה הבריטית באוקיינוס ההודי',
  'British Virgin Islands': 'איי הבתולה הבריטיים',
  'Brunei': 'ברוניי',
  'Bulgaria': 'בולגריה',
  'Burkina Faso': 'בורקינה פאסו',
  'Burundi': 'בורונדי',
  'Cambodia': 'קמבודיה',
  'Cameroon': 'קמרון',
  'Canada': 'קנדה',
  'Cape Verde': 'כף ורדה',
  'Cayman Islands': 'איי קיימן',
  'Central African Republic': 'הרפובליקה המרכז אפריקאית',
  'Chad': 'צ\'אד',
  'Chile': 'צ\'ילה',
  'China': 'סין',
  'Christmas Island': 'אי חג המולד',
  'Cocos Islands': 'איי קוקוס',
  'Colombia': 'קולומביה',
  'Comoros': 'קומורו',
  'Cook Islands': 'איי קוק',
  'Costa Rica': 'קוסטה ריקה',
  'Croatia': 'קרואטיה',
  'Cuba': 'קובה',
  'Curacao': 'קוראסאו',
  'Cyprus': 'קפריסין',
  'Czech Republic': 'צ\'כיה',
  'Democratic Republic of the Congo': 'הרפובליקה הדמוקרטית של קונגו',
  'Denmark': 'דנמרק',
  'Djibouti': 'ג\'יבוטי',
  'Dominica': 'דומיניקה',
  'Dominican Republic': 'הרפובליקה הדומיניקנית',
  'East Timor': 'מזרח טימור',
  'Ecuador': 'אקוודור',
  'Egypt': 'מצרים',
  'El Salvador': 'אל סלבדור',
  'Equatorial Guinea': 'גינאה המשוונית',
  'Eritrea': 'אריתריאה',
  'Estonia': 'אסטוניה',
  'Ethiopia': 'אתיופיה',
  'Falkland Islands': 'איי פוקלנד',
  'Faroe Islands': 'איי פארו',
  'Fiji': 'פיג\'י',
  'Finland': 'פינלנד',
  'France': 'צרפת',
  'French Polynesia': 'פולינזיה הצרפתית',
  'Gabon': 'גבון',
  'Gambia': 'גמביה',
  'Georgia': 'גאורגיה',
  'Germany': 'גרמניה',
  'Ghana': 'גאנה',
  'Gibraltar': 'גיברלטר',
  'Greece': 'יוון',
  'Greenland': 'גרינלנד',
  'Grenada': 'גרנדה',
  'Guam': 'גואם',
  'Guatemala': 'גואטמלה',
  'Guernsey': 'גרנזי',
  'Guinea': 'גינאה',
  'Guinea-Bissau': 'גינאה ביסאו',
  'Guyana': 'גיאנה',
  'Haiti': 'האיטי',
  'Honduras': 'הונדורס',
  'Hong Kong': 'הונג קונג',
  'Hungary': 'הונגריה',
  'Iceland': 'איסלנד',
  'India': 'הודו',
  'Indonesia': 'אינדונזיה',
  'Iran': 'איראן',
  'Iraq': 'עיראק',
  'Ireland': 'אירלנד',
  'Isle of Man': 'האי מאן',
  'Israel': 'ישראל',
  'Italy': 'איטליה',
  'Ivory Coast': 'חוף השנהב',
  'Jamaica': 'ג\'מייקה',
  'Japan': 'יפן',
  'Jersey': 'ג\'רזי',
  'Jordan': 'ירדן',
  'Kazakhstan': 'קזחסטן',
  'Kenya': 'קניה',
  'Kiribati': 'קיריבטי',
  'Kosovo': 'קוסובו',
  'Kuwait': 'כווית',
  'Kyrgyzstan': 'קירגיזסטן',
  'Laos': 'לאוס',
  'Latvia': 'לטביה',
  'Lebanon': 'לבנון',
  'Lesotho': 'לסוטו',
  'Liberia': 'ליבריה',
  'Libya': 'לוב',
  'Liechtenstein': 'ליכטנשטיין',
  'Lithuania': 'ליטא',
  'Luxembourg': 'לוקסמבורג',
  'Macau': 'מקאו',
  'Macedonia': 'מקדוניה',
  'Madagascar': 'מדגסקר',
  'Malawi': 'מלאווי',
  'Malaysia': 'מלזיה',
  'Maldives': 'האיים המלדיביים',
  'Mali': 'מאלי',
  'Malta': 'מלטה',
  'Marshall Islands': 'איי מרשל',
  'Mauritania': 'מאוריטניה',
  'Mauritius': 'מאוריציוס',
  'Mayotte': 'מיוט',
  'Mexico': 'מקסיקו',
  'Micronesia': 'מיקרונזיה',
  'Moldova': 'מולדובה',
  'Monaco': 'מונקו',
  'Mongolia': 'מונגוליה',
  'Montenegro': 'מונטנגרו',
  'Montserrat': 'מונטסראט',
  'Morocco': 'מרוקו',
  'Mozambique': 'מוזמביק',
  'Myanmar': 'מיאנמר',
  'Namibia': 'נמיביה',
  'Nauru': 'נאורו',
  'Nepal': 'נפאל',
  'Netherlands': 'הולנד',
  'Netherlands Antilles': 'האנטילים ההולנדיים',
  'New Caledonia': 'קלדוניה החדשה',
  'New Zealand': 'ניו זילנד',
  'Nicaragua': 'ניקרגואה',
  'Niger': 'ניז\'ר',
  'Nigeria': 'ניגריה',
  'Niue': 'ניואה',
  'North Korea': 'קוריאה הצפונית',
  'Northern Mariana Islands': 'איי מריאנה הצפוניים',
  'Norway': 'נורווגיה',
  'Oman': 'עומאן',
  'Pakistan': 'פקיסטן',
  'Palau': 'פלאו',
  'Palestine': 'פלסטין',
  'Panama': 'פנמה',
  'Papua New Guinea': 'פפואה גינאה החדשה',
  'Paraguay': 'פרגוואי',
  'Peru': 'פרו',
  'Philippines': 'הפיליפינים',
  'Pitcairn': 'פיטקרן',
  'Poland': 'פולין',
  'Portugal': 'פורטוגל',
  'Puerto Rico': 'פוארטו ריקו',
  'Qatar': 'קטאר',
  'Republic of the Congo': 'הרפובליקה של קונגו',
  'Reunion': 'ראוניון',
  'Romania': 'רומניה',
  'Russia': 'רוסיה',
  'Rwanda': 'רואנדה',
  'Saint Barthelemy': 'סנט ברתולומיאו',
  'Saint Helena': 'סנט הלנה',
  'Saint Kitts and Nevis': 'סנט קיטס ונוויס',
  'Saint Lucia': 'סנט לוסיה',
  'Saint Martin': 'סנט מרטין',
  'Saint Pierre and Miquelon': 'סנט פייר ומיקלון',
  'Saint Vincent and the Grenadines': 'סנט וינסנט והגרנדינים',
  'Samoa': 'סמואה',
  'San Marino': 'סן מרינו',
  'Sao Tome and Principe': 'סאו טומה ופרינסיפה',
  'Saudi Arabia': 'ערב הסעודית',
  'Senegal': 'סנגל',
  'Serbia': 'סרביה',
  'Seychelles': 'איי סיישל',
  'Sierra Leone': 'סיירה לאון',
  'Singapore': 'סינגפור',
  'Sint Maarten': 'סנט מארטן',
  'Slovakia': 'סלובקיה',
  'Slovenia': 'סלובניה',
  'Solomon Islands': 'איי שלמה',
  'Somalia': 'סומליה',
  'South Africa': 'דרום אפריקה',
  'South Korea': 'קוריאה הדרומית',
  'South Sudan': 'דרום סודן',
  'Spain': 'ספרד',
  'Sri Lanka': 'סרי לנקה',
  'Sudan': 'סודן',
  'Suriname': 'סורינאם',
  'Svalbard and Jan Mayen': 'סבאלברד ויאן מאיין',
  'Swaziland': 'סווזילנד',
  'Sweden': 'שוודיה',
  'Switzerland': 'שוויץ',
  'Syria': 'סוריה',
  'Taiwan': 'טייוואן',
  'Tajikistan': 'טג\'יקיסטן',
  'Tanzania': 'טנזניה',
  'Thailand': 'תאילנד',
  'Togo': 'טוגו',
  'Tokelau': 'טוקלאו',
  'Tonga': 'טונגה',
  'Trinidad and Tobago': 'טרינידד וטובגו',
  'Tunisia': 'תוניסיה',
  'Turkey': 'טורקיה',
  'Turkmenistan': 'טורקמניסטן',
  'Turks and Caicos Islands': 'איי טרקס וקאיקוס',
  'Tuvalu': 'טובאלו',
  'U.S. Virgin Islands': 'איי הבתולה של ארה"ב',
  'Uganda': 'אוגנדה',
  'Ukraine': 'אוקראינה',
  'United Arab Emirates': 'איחוד האמירויות הערביות',
  'United Kingdom': 'בריטניה',
  'United States': 'ארצות הברית',
  'Uruguay': 'אורוגוואי',
  'Uzbekistan': 'אוזבקיסטן',
  'Vanuatu': 'ונואטו',
  'Vatican': 'הוותיקן',
  'Venezuela': 'ונצואלה',
  'Vietnam': 'וייטנאם',
  'Wallis and Futuna': 'וואליס ופוטונה',
  'Western Sahara': 'סהרה המערבית',
  'Yemen': 'תימן',
  'Zambia': 'זמביה',
  'Zimbabwe': 'זימבבואה',
};

export function getCountryName(country: string, isRTL: boolean): string {
  if (!isRTL) return country;
  return COUNTRY_NAMES_HEBREW[country] || country;
}
