"""Alembic script template.

This template is used by Alembic to generate new migration files.
You can customize it to change the structure of the migration files.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09debd51d5a6'
down_revision = '8adb4c86c340'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reminder_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reminder_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reminder_id'], ['reminders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reminder_notes_reminder_id'), 'reminder_notes', ['reminder_id'], unique=False)
    op.create_index(op.f('ix_reminder_notes_user_id'), 'reminder_notes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reminder_notes_user_id'), table_name='reminder_notes')
    op.drop_index(op.f('ix_reminder_notes_reminder_id'), table_name='reminder_notes')
    op.drop_table('reminder_notes')
    # ### end Alembic commands ###
