"""add archive fields to applications

Revision ID: 20251021_archive
Revises: a124a47fd4fb
Create Date: 2025-10-21 06:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20251021_archive'
down_revision = 'a124a47fd4fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('is_archived', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('applications', sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_applications_is_archived'), 'applications', ['is_archived'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_is_archived'), table_name='applications')
    op.drop_column('applications', 'archived_at')
    op.drop_column('applications', 'is_archived')
    # ### end Alembic commands ###
