"""Alembic script template.

This template is used by Alembic to generate new migration files.
You can customize it to change the structure of the migration files.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c7de1a9b0c7'
down_revision = '20251106_banned_entities'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('application_attachments_application_id_fkey'), 'application_attachments', type_='foreignkey')
    op.drop_constraint(op.f('applications_user_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_job_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_resume_id_fkey'), 'applications', type_='foreignkey')
    op.drop_index(op.f('idx_banned_entities_active'), table_name='banned_entities')
    op.drop_index(op.f('idx_banned_entities_lookup'), table_name='banned_entities')
    op.drop_index(op.f('idx_banned_entities_type'), table_name='banned_entities')
    op.drop_index(op.f('idx_banned_entities_user'), table_name='banned_entities')
    op.drop_index(op.f('idx_banned_entities_value'), table_name='banned_entities')
    op.create_index(op.f('ix_banned_entities_banned_user_id'), 'banned_entities', ['banned_user_id'], unique=False)
    op.create_index(op.f('ix_banned_entities_entity_type'), 'banned_entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_banned_entities_entity_value'), 'banned_entities', ['entity_value'], unique=False)
    op.create_index(op.f('ix_banned_entities_is_active'), 'banned_entities', ['is_active'], unique=False)
    op.drop_constraint(op.f('email_actions_user_id_fkey'), 'email_actions', type_='foreignkey')
    op.add_column('jobs', sa.Column('is_archived', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_jobs_is_archived'), 'jobs', ['is_archived'], unique=False)
    op.drop_constraint(op.f('jobs_user_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_constraint(op.f('jobs_company_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_index(op.f('idx_llm_usage_model'), table_name='llm_usage')
    op.drop_index(op.f('idx_llm_usage_provider'), table_name='llm_usage')
    op.drop_index(op.f('idx_llm_usage_success'), table_name='llm_usage')
    op.drop_index(op.f('idx_llm_usage_timestamp'), table_name='llm_usage')
    op.drop_index(op.f('idx_llm_usage_user_id'), table_name='llm_usage')
    op.create_index(op.f('ix_llm_usage_model'), 'llm_usage', ['model'], unique=False)
    op.create_index(op.f('ix_llm_usage_provider'), 'llm_usage', ['provider'], unique=False)
    op.create_index(op.f('ix_llm_usage_success'), 'llm_usage', ['success'], unique=False)
    op.create_index(op.f('ix_llm_usage_timestamp'), 'llm_usage', ['timestamp'], unique=False)
    op.create_index(op.f('ix_llm_usage_user_id'), 'llm_usage', ['user_id'], unique=False)
    op.drop_constraint(op.f('match_results_resume_id_fkey'), 'match_results', type_='foreignkey')
    op.drop_constraint(op.f('match_results_job_id_fkey'), 'match_results', type_='foreignkey')
    op.drop_constraint(op.f('match_results_user_id_fkey'), 'match_results', type_='foreignkey')
    op.drop_constraint(op.f('notes_application_id_fkey'), 'notes', type_='foreignkey')
    op.drop_constraint(op.f('notes_user_id_fkey'), 'notes', type_='foreignkey')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(op.f('resumes_user_id_fkey'), 'resumes', type_='foreignkey')
    op.drop_constraint(op.f('stages_application_id_fkey'), 'stages', type_='foreignkey')
    op.drop_constraint(op.f('user_preferences_user_id_fkey'), 'user_preferences', type_='foreignkey')
    op.alter_column('users', 'github_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=200),
               existing_nullable=True)
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.alter_column('users', 'github_url',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.create_foreign_key(op.f('user_preferences_user_id_fkey'), 'user_preferences', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('stages_application_id_fkey'), 'stages', 'applications', ['application_id'], ['id'])
    op.create_foreign_key(op.f('resumes_user_id_fkey'), 'resumes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_foreign_key(op.f('notes_user_id_fkey'), 'notes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('notes_application_id_fkey'), 'notes', 'applications', ['application_id'], ['id'])
    op.create_foreign_key(op.f('match_results_user_id_fkey'), 'match_results', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('match_results_job_id_fkey'), 'match_results', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(op.f('match_results_resume_id_fkey'), 'match_results', 'resumes', ['resume_id'], ['id'])
    op.drop_index(op.f('ix_llm_usage_user_id'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_timestamp'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_success'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_provider'), table_name='llm_usage')
    op.drop_index(op.f('ix_llm_usage_model'), table_name='llm_usage')
    op.create_index(op.f('idx_llm_usage_user_id'), 'llm_usage', ['user_id'], unique=False)
    op.create_index(op.f('idx_llm_usage_timestamp'), 'llm_usage', ['timestamp'], unique=False)
    op.create_index(op.f('idx_llm_usage_success'), 'llm_usage', ['success'], unique=False)
    op.create_index(op.f('idx_llm_usage_provider'), 'llm_usage', ['provider'], unique=False)
    op.create_index(op.f('idx_llm_usage_model'), 'llm_usage', ['model'], unique=False)
    op.create_foreign_key(op.f('jobs_company_id_fkey'), 'jobs', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(op.f('jobs_user_id_fkey'), 'jobs', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_jobs_is_archived'), table_name='jobs')
    op.drop_column('jobs', 'is_archived')
    op.create_foreign_key(op.f('email_actions_user_id_fkey'), 'email_actions', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_banned_entities_is_active'), table_name='banned_entities')
    op.drop_index(op.f('ix_banned_entities_entity_value'), table_name='banned_entities')
    op.drop_index(op.f('ix_banned_entities_entity_type'), table_name='banned_entities')
    op.drop_index(op.f('ix_banned_entities_banned_user_id'), table_name='banned_entities')
    op.create_index(op.f('idx_banned_entities_value'), 'banned_entities', ['entity_value'], unique=False)
    op.create_index(op.f('idx_banned_entities_user'), 'banned_entities', ['banned_user_id'], unique=False)
    op.create_index(op.f('idx_banned_entities_type'), 'banned_entities', ['entity_type'], unique=False)
    op.create_index(op.f('idx_banned_entities_lookup'), 'banned_entities', ['entity_type', 'entity_value', 'is_active'], unique=False)
    op.create_index(op.f('idx_banned_entities_active'), 'banned_entities', ['is_active'], unique=False)
    op.create_foreign_key(op.f('applications_resume_id_fkey'), 'applications', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(op.f('applications_job_id_fkey'), 'applications', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(op.f('applications_user_id_fkey'), 'applications', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('application_attachments_application_id_fkey'), 'application_attachments', 'applications', ['application_id'], ['id'])
    # ### end Alembic commands ###
