"""Alembic script template.

This template is used by Alembic to generate new migration files.
You can customize it to change the structure of the migration files.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a124a47fd4fb'
down_revision = '09debd51d5a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'reminder_notes',
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    )
    # backfill existing rows; use created_at (or now()) as you prefer
    op.execute("UPDATE reminder_notes SET updated_at = created_at WHERE updated_at IS NULL")
    # now enforce NOT NULL
    op.alter_column(
        'reminder_notes',
        'updated_at',
        existing_type=sa.DateTime(timezone=True),
        nullable=False,
    )
    op.drop_constraint(op.f('reminder_notes_reminder_id_fkey'), 'reminder_notes', type_='foreignkey')
    op.create_foreign_key(None, 'reminder_notes', 'reminders', ['reminder_id'], ['id'])
    op.add_column('reminders', sa.Column('meet_url', sa.String(length=1000), nullable=True))
    op.create_index(op.f('ix_reminders_google_event_id'), 'reminders', ['google_event_id'], unique=False)
    op.create_unique_constraint('uq_user_google_event', 'reminders', ['user_id', 'google_event_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_google_event', 'reminders', type_='unique')
    op.drop_index(op.f('ix_reminders_google_event_id'), table_name='reminders')
    op.drop_column('reminders', 'meet_url')
    op.drop_constraint(None, 'reminder_notes', type_='foreignkey')
    op.create_foreign_key(op.f('reminder_notes_reminder_id_fkey'), 'reminder_notes', 'reminders', ['reminder_id'], ['id'], ondelete='CASCADE')
    op.drop_column('reminder_notes', 'updated_at')
    # ### end Alembic commands ###
