"""add source field to applications

Revision ID: b4d5a72fc891
Revises: ee4476447a78
Create Date: 2025-09-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4d5a72fc891'
down_revision = 'ee4476447a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('source', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_applications_source'), 'applications', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_applications_source'), table_name='applications')
    op.drop_column('applications', 'source')
    # ### end Alembic commands ###