"""Alembic script template.

This template is used by Alembic to generate new migration files.
You can customize it to change the structure of the migration files.

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c88765428c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_attachments_created_at'), table_name='application_attachments')
    op.drop_constraint(op.f('application_attachments_application_id_fkey'), 'application_attachments', type_='foreignkey')
    op.drop_index(op.f('ix_applications_created_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_updated_at'), table_name='applications')
    op.drop_index(op.f('ix_applications_user_status_created'), table_name='applications')
    op.create_index(op.f('ix_applications_job_id'), 'applications', ['job_id'], unique=False)
    op.create_index(op.f('ix_applications_resume_id'), 'applications', ['resume_id'], unique=False)
    op.drop_constraint(op.f('applications_user_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_resume_id_fkey'), 'applications', type_='foreignkey')
    op.drop_constraint(op.f('applications_job_id_fkey'), 'applications', type_='foreignkey')
    op.drop_index(op.f('uq_companies_name_lower'), table_name='companies')
    op.drop_constraint(op.f('email_actions_token_key'), 'email_actions', type_='unique')
    op.drop_index(op.f('ix_email_actions_token'), table_name='email_actions')
    op.create_index(op.f('ix_email_actions_token'), 'email_actions', ['token'], unique=True)
    op.drop_constraint(op.f('email_actions_user_id_fkey'), 'email_actions', type_='foreignkey')
    op.drop_index(op.f('ix_jobs_content_fts'), table_name='jobs', postgresql_using='gin')
    op.drop_index(op.f('ix_jobs_description_fts'), table_name='jobs', postgresql_using='gin')
    op.drop_index(op.f('ix_jobs_title_fts'), table_name='jobs', postgresql_using='gin')
    op.create_index(op.f('ix_jobs_company_id'), 'jobs', ['company_id'], unique=False)
    op.drop_constraint(op.f('jobs_company_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_constraint(op.f('jobs_user_id_fkey'), 'jobs', type_='foreignkey')
    op.drop_index(op.f('ix_match_results_score'), table_name='match_results')
    op.drop_constraint(op.f('match_results_resume_id_fkey'), 'match_results', type_='foreignkey')
    op.drop_constraint(op.f('match_results_user_id_fkey'), 'match_results', type_='foreignkey')
    op.drop_constraint(op.f('match_results_job_id_fkey'), 'match_results', type_='foreignkey')
    op.drop_index(op.f('ix_notes_created_at'), table_name='notes')
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.drop_constraint(op.f('notes_user_id_fkey'), 'notes', type_='foreignkey')
    op.drop_constraint(op.f('notes_application_id_fkey'), 'notes', type_='foreignkey')
    op.drop_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.drop_index(op.f('ix_resumes_created_at'), table_name='resumes')
    op.drop_constraint(op.f('resumes_user_id_fkey'), 'resumes', type_='foreignkey')
    op.drop_index(op.f('ix_stages_scheduled_at'), table_name='stages')
    op.drop_constraint(op.f('stages_application_id_fkey'), 'stages', type_='foreignkey')
    op.drop_index(op.f('ix_user_preferences_key'), table_name='user_preferences')
    op.drop_constraint(op.f('uq_user_preferences_user_key'), 'user_preferences', type_='unique')
    op.drop_constraint(op.f('user_preferences_user_id_fkey'), 'user_preferences', type_='foreignkey')
    op.alter_column('users', 'full_name',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'full_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.create_foreign_key(op.f('user_preferences_user_id_fkey'), 'user_preferences', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_user_preferences_user_key'), 'user_preferences', ['user_id', 'preference_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_user_preferences_key'), 'user_preferences', ['preference_key'], unique=False)
    op.create_foreign_key(op.f('stages_application_id_fkey'), 'stages', 'applications', ['application_id'], ['id'])
    op.create_index(op.f('ix_stages_scheduled_at'), 'stages', ['scheduled_at'], unique=False)
    op.create_foreign_key(op.f('resumes_user_id_fkey'), 'resumes', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_resumes_created_at'), 'resumes', ['created_at'], unique=False)
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=False)
    op.create_unique_constraint(op.f('refresh_tokens_jti_key'), 'refresh_tokens', ['jti'], postgresql_nulls_not_distinct=False)
    op.create_foreign_key(op.f('notes_application_id_fkey'), 'notes', 'applications', ['application_id'], ['id'])
    op.create_foreign_key(op.f('notes_user_id_fkey'), 'notes', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.create_index(op.f('ix_notes_created_at'), 'notes', ['created_at'], unique=False)
    op.create_foreign_key(op.f('match_results_job_id_fkey'), 'match_results', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(op.f('match_results_user_id_fkey'), 'match_results', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('match_results_resume_id_fkey'), 'match_results', 'resumes', ['resume_id'], ['id'])
    op.create_index(op.f('ix_match_results_score'), 'match_results', ['score'], unique=False)
    op.create_foreign_key(op.f('jobs_user_id_fkey'), 'jobs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('jobs_company_id_fkey'), 'jobs', 'companies', ['company_id'], ['id'])
    op.drop_index(op.f('ix_jobs_company_id'), table_name='jobs')
    op.create_index(op.f('ix_jobs_title_fts'), 'jobs', [sa.literal_column("to_tsvector('english'::regconfig, title::text)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_jobs_description_fts'), 'jobs', [sa.literal_column("to_tsvector('english'::regconfig, description)")], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_jobs_content_fts'), 'jobs', [sa.literal_column("to_tsvector('english'::regconfig, (title::text || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.create_foreign_key(op.f('email_actions_user_id_fkey'), 'email_actions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_email_actions_token'), table_name='email_actions')
    op.create_index(op.f('ix_email_actions_token'), 'email_actions', ['token'], unique=False)
    op.create_unique_constraint(op.f('email_actions_token_key'), 'email_actions', ['token'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_companies_name_lower'), 'companies', [sa.literal_column('lower(name::text)')], unique=True)
    op.create_foreign_key(op.f('applications_job_id_fkey'), 'applications', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(op.f('applications_resume_id_fkey'), 'applications', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(op.f('applications_user_id_fkey'), 'applications', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_applications_resume_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_job_id'), table_name='applications')
    op.create_index(op.f('ix_applications_user_status_created'), 'applications', ['user_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_applications_updated_at'), 'applications', ['updated_at'], unique=False)
    op.create_index(op.f('ix_applications_created_at'), 'applications', ['created_at'], unique=False)
    op.create_foreign_key(op.f('application_attachments_application_id_fkey'), 'application_attachments', 'applications', ['application_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_application_attachments_created_at'), 'application_attachments', ['created_at'], unique=False)
    # ### end Alembic commands ###
