"""add user profiles table

Revision ID: f1a2b3c4d5e6
Revises: b4d5a72fc891
Create Date: 2024-12-21 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import UUID, JSON


# revision identifiers, used by Alembic.
revision = 'f1a2b3c4d5e6'
down_revision = 'b4d5a72fc891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
        sa.Column('id', UUID(as_uuid=True), nullable=False),
        sa.Column('user_id', UUID(as_uuid=True), nullable=False),
        sa.Column('preferred_locations', JSON(), nullable=True),
        sa.Column('country', sa.String(), nullable=True),
        sa.Column('remote_preference', sa.String(), nullable=True),
        sa.Column('target_roles', JSON(), nullable=True),
        sa.Column('target_industries', JSON(), nullable=True),
        sa.Column('experience_level', sa.String(), nullable=True),
        sa.Column('skills', JSON(), nullable=True),
        sa.Column('career_goals', JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###