"""add document_type to attachments

Revision ID: f2a3b4c5d6e7
Revises: f1a2b3c4d5e6
Create Date: 2025-09-28 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2a3b4c5d6e7'
down_revision = 'f1a2b3c4d5e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application_attachments', sa.Column('document_type', sa.String(length=32), nullable=True, default='other'))
    op.create_index(op.f('ix_application_attachments_document_type'), 'application_attachments', ['document_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_attachments_document_type'), table_name='application_attachments')
    op.drop_column('application_attachments', 'document_type')
    # ### end Alembic commands ###