"""remove salary fields from user profiles

Revision ID: c7f8b9e1a2d3
Revises: b4d5a72fc891
Create Date: 2024-12-21 16:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f8b9e1a2d3'
down_revision = 'b4d5a72fc891'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'min_salary')
    op.drop_column('user_profiles', 'max_salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('min_salary', sa.INTEGER(), nullable=True))
    op.add_column('user_profiles', sa.Column('max_salary', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###