class ApplicationNotFound(Exception): ...
class StageNotFound(Exception): ...
class AttachmentNotFound(Exception): ...
class BadRequest(Exception):
    def __init__(self, detail: str): self.detail = detail
