from __future__ import annotations
from typing import Optional, List, Tuple
from uuid import UUID
from .dto import ApplicationDTO, StageDTO, NoteDTO, AttachmentDTO, CardRowDTO, JobTinyDTO

class IGuardRepo:
    def ensure_job_exists(self, job_id: UUID) -> bool: ...
    def ensure_resume_exists(self, resume_id: UUID) -> bool: ...
    def get_owned_app(self, app_id: UUID, user_id: UUID) -> ApplicationDTO: ...

class IApplicationRepo(IGuardRepo):
    def find_by_user_and_job(self, user_id: UUID, job_id: UUID) -> Optional[ApplicationDTO]: ...
    def create(self, *, user_id: UUID, job_id: UUID, resume_id: Optional[UUID], status: str, source: Optional[str]) -> ApplicationDTO: ...
    def update(self, app_id: UUID, data: dict) -> ApplicationDTO: ...
    def list_paginated(
        self, *, user_id: UUID, status: Optional[str], q: str, sort: str, order: str, page: int, page_size: int
    ) -> Tuple[List[ApplicationDTO], int]:
        ...
    def get_used_statuses(self, user_id: UUID) -> List[str]: ...
    def list_cards(self, user_id: UUID, status: Optional[str]) -> List[CardRowDTO]: ...
    def delete_cascade(self, app_id: UUID, user_id: UUID) -> None: ...
    def list_with_stages_dict(self, user_id: UUID) -> List[dict]: ...
    def get_detail(
        self, user_id: UUID, app_id: UUID
    ) -> tuple[ApplicationDTO, Optional[JobTinyDTO], Optional[str], Optional[str], Optional[str], List[StageDTO], List[NoteDTO], List[AttachmentDTO]]:
        ...

class IStageRepo(IGuardRepo):
    def add(self, app_id: UUID, name: str, scheduled_at=None, outcome=None, notes=None) -> StageDTO: ...
    def list_for_app(self, app_id: UUID) -> List[StageDTO]: ...
    def get(self, app_id: UUID, stage_id: UUID) -> StageDTO: ...
    def update_partial(self, stage_id: UUID, data: dict) -> StageDTO: ...
    def delete(self, stage_id: UUID) -> None: ...

class INoteRepo(IGuardRepo):
    def add(self, app_id: UUID, body: str) -> NoteDTO: ...
    def list_for_app(self, app_id: UUID) -> List[NoteDTO]: ...

class IAttachmentRepo(IGuardRepo):
    def create(self, *, app_id: UUID, filename: str, file_size: int, content_type: str, file_path: str, document_type: Optional[str]) -> AttachmentDTO: ...
    def list_for_app(self, app_id: UUID) -> List[AttachmentDTO]: ...
    def get(self, attachment_id: UUID) -> AttachmentDTO: ...
    def delete(self, attachment_id: UUID) -> None: ...
